name: Docker Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag name
        id: tag
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            TAG_NAME=$(echo ${{ github.ref }} | sed 's|refs/tags/||')
            echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
            echo "is_tag=true" >> $GITHUB_OUTPUT
          else
            echo "is_tag=false" >> $GITHUB_OUTPUT
            echo "Not a tag push, skipping..."
            exit 1
          fi

      - name: Debug information
        run: |
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_REF_NAME: ${{ github.ref_name }}"
          echo "GITHUB_REF_TYPE: ${{ github.ref_type }}"
          echo "Extracted tag: ${{ steps.tag.outputs.tag_name }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/cloud-security-toolkit:${{ steps.tag.outputs.tag_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/cloud-security-toolkit:latest

      - name: Display pushed tags
        run: |
          echo "Successfully pushed:"
          echo "- ${{ secrets.DOCKERHUB_USERNAME }}/cloud-security-toolkit:${{ steps.tag.outputs.tag_name }}"
          echo "- ${{ secrets.DOCKERHUB_USERNAME }}/cloud-security-toolkit:latest"
